global:
  scrape_interval: 5s
  evaluation_interval: 10s
  external_labels:
    monitor: "my-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]

  - job_name: "node-exporter"
    static_configs:
    - targets: ["node-exporter:9100"]
      labels:
        instance: "172.23.170.252"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
         instance: "172.23.170.252"

  - job_name: "influxdb-exporter"
    static_configs:
    - targets: ["172.23.170.252:9275"]
